[package]
name = "swiss-cv"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Frédéric Arroyo"]
license = "MIT"
description = ""
homepage = ""
repository = ""
keywords = []
categories = []
disciplines = []
# compiler = ""
exclude = [
    ".github",
    "docs",
    "scripts",
    "tests",
    ".typstignore",
    "Justfile",
    "thumbnail-dark.svg",
    "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
